name: Workflow

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ vars.CHANNEL_ID }}
          slack-message: "Hello 👋 World 🌎"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
